name: Generate sitemap

on:
  push:
    branches: [ master ]

permissions:
  contents: write   # 允许这个 workflow 往仓库里提交

jobs:
  sitemap_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # 这个 action 需要完整 commit 历史来算 <lastmod>

      - name: Generate sitemap.xml
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://powerxlab.pages.dev/
          # 如果你的站点根目录不是仓库根（比如在 /public），这里加：
          # path-to-root: public

      - name: Commit sitemap.xml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Update sitemap" || echo "No changes to commit"
          git push